import { GithubBlogShowPathSrc } from "@/utills/config/config.type";
import GithubBlogConfig from "@/utills/config/github-blog.config";
const userConfig = GithubBlogConfig({
    // site domain
    // domain: 'http://localhost:3000',
    domain: 'https://alie-promotion-blog.vercel.app',

    // site metadata
    title: 'alie-promotion-blog',
    dynamicTitle: true,
    description: 'Generated by create next app',
    webSiteImage: 'https://avatars.githubusercontent.com/u/102360897?v=4',

    git: {
        repository: 'alie-promotion-blog-storage',
        owner: 'jun-young1993'
    },
    headerMenus: [{
        type: 'markdown-viewer',
        path: '/',
        title: 'About Me'
    }],
    githubBlogShowPaths: [
        '3D Printing & Additive Manufacturing',
        'Barebone & Mini PC',
        'Cleaning Appliances',
        'Commercial Appliances',
        'Computer & Office',
        'Computer Cleaners',
        'Computer Components',
        'Computer Peripherals',
        'Desktops & AIO',
        'Home Appliance Parts',
        'Home Appliances',
        'Household Appliances',
        'Kitchen Appliances',
        'Laptop Parts & Accessories',
        'Laptops',
        'Major Appliances',
        'Networking',
        'Personal Care Appliances',
        'Storage Device',
        'Tablet Accessories & Parts',
        'Tablets'
    ].map((item) => {
        return {
            type: 'contents',
            path: item,
        }
    }),
    userSitemap: [
        'ads.txt'
    ],
    ignorePaths: [

    ],

    nextConfig: {
        cache: {
            revalidate : 1
        }
    },


    // We use wikiLinks such as [[path]] and ![[test.png]]. Please enter the repository's path.
    wikiLink: 'images',

    // Whether to use table of contents. The default value is true
    tableOfContents: true,
    // This specifies the heading tag number as a string for the table of contents.
    // The default value is up to h3, and it can be spcified up to '6'
    tableOfContentsMaxLevel: '3'
});
export default userConfig;